### ISSUE TITLE
Font & color issue with VSC

### ISSUE THREAD

**Issue by Bana99** [llatigid/Pushkin-is-White-Theme#2]
Hello, 

Thanks for this theme it works great. However do you know how can I have the exact same parameters as yours. For example the bold "var" is less thicker then yours. Police is also different. Sadly I do not know how to change them myself.

Cheers

**Comment by jsfag** [comment]
Hello! The FiraCode font is used in the screenshots. [Project link](https://github.com/tonsky/FiraCode).

**Comment by markmysourcecode** [comment]
Greetings,

Thanks for your hard work, this theme is awesome.
I was wondering if we can have another version of the black theme, like a terminal.
a black background and just white text, maybe except for the comments.
I don't know how to change it them myself too, but as I can see I can read some of your json file.

Thanks.

**Comment by jsfag** [comment]
Hello.
Do you mean without an additional colouring of the syntax and at the same time without muting (to soften the contrast) the white colour of the font, the opposite of the White theme?
