### ISSUE TITLE
better LaTeX syntax highlighting

### ISSUE THREAD

**Issue by miccferr** [llatigid/Pushkin-is-White-Theme#6]
Hi,

first of all thank you for the super-sleek theme! 

I was wondering how to enhance the support for LaTeX syntax highlighting. 

So far the theme manages to colour certain keywords but not most, resulting in a slightly harder-to-parse text than other themes (see below comparison with [Material Theme](https://github.com/equinusocio/material-theme).

<img width="384" alt="screen shot 2017-09-28 at 14 36 48" src="https://user-images.githubusercontent.com/3855777/30969866-8a734060-a45b-11e7-846b-075349afa17c.png"><img width="388" alt="screen shot 2017-09-28 at 14 37 00" src="https://user-images.githubusercontent.com/3855777/30969868-8c13e67c-a45b-11e7-963e-96e023a97992.png">

I'm happy to contribute, but I'm a bit confused on where to start. Looking at [this file](https://github.com/llatigid/Pushkin-is-White-Theme/blob/master/themes/pushkin-is-white-theme.json#L106)  seems like certain languages are dealt with in a quite specific way. Is that the way to go? Do you have any pointers on how I can help tweaking it to accomodate a better LaTeX colouring?

Thank you in advance. 

Cheers,
m.

**Comment by jsfag** [comment]
Hello! Thanks for the feedback. I'm glad that you like the theme. The vscode syntax colouring is good, but sometimes it can surprise.

To tweak the syntax, you would need to use a built-in tool: 'Inspect TM Scopes', via 'Command Palette' — Ctrl Shift P/⇧⌘P.

Also, you may need an official theme colour reference — https://code.visualstudio.com/docs/getstarted/theme-color-reference.

**Comment by miccferr** [comment]
Hey there!

Apologies if it took me a while, I've create a PR adding some LateX syntax highlighting for the White Theme. 
It's inspired by Vim's [Pencil](https://github.com/reedes/vim-pencil/) color scheme. 

<img width="734" alt="screen shot 2017-11-28 at 13 45 48" src="https://user-images.githubusercontent.com/3855777/33323478-83d06d28-d444-11e7-9b19-ac0e0adc3c8b.png">
 
Hope you like it!

**Comment by jsfag** [comment]
Hello! Of course, I've liked it, pretty well, thank you!
